version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.eclipse.jetty:jetty-bom
    versions:
    - 10.0.0
    - 11.0.1
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - 2.4.2
  - dependency-name: org.apache.cxf:cxf-rt-features-logging
    versions:
    - 3.4.2
  - dependency-name: org.apache.cxf:cxf-spring-boot-starter-jaxws
    versions:
    - 3.4.2
  - dependency-name: org.apache.cxf:cxf-rt-frontend-jaxws
    versions:
    - 3.4.2
  - dependency-name: org.apache.cxf:cxf-rt-transports-http
    versions:
    - 3.4.2
