language: java
jdk: openjdk11

jobs:
    include:
        - stage: build
          script: ./gradlew clean assemble
        - stage: test
          script: ./gradlew check
          

stages:
    - build
    - test

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
