language: java
jdk: openjdk11

jobs:
    include:
        - stage: build
          script: ./gradlew clean assemble
        - stage: test
          script: ./gradlew test
          

stages:
    - build
    - test

